---
apiVersion: v1
kind: Namespace
metadata:
  name: azure-arc-onboarding
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-arc-onboarding
  namespace: azure-arc-onboarding
data:
  TENANT_ID: "{{TenantID}}"
  SUBSCRIPTION_ID: "{{SubscriptionID}}"
  RESOURCE_GROUP: "{{ResourceGroup}}"
  CONNECTED_CLUSTER: "{{ClusterName}}"
  LOCATION: "{{Location}}"
  CLIENT_ID: "{{ClientID}}"
  CLIENT_SECRET: "{{ClientSecret}}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-arc-onboarding
  namespace: azure-arc-onboarding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-arc-onboarding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: azure-arc-onboarding
    namespace: azure-arc-onboarding
---
apiVersion: batch/v1
kind: Job
metadata:
  name: azure-arc-onboarding
  namespace: azure-arc-onboarding
spec:
  template:
    spec:
      serviceAccountName: azure-arc-onboarding
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: azure-arc-onboarding
        image: arck8sonboarding.azurecr.io/arck8sonboarding:v0.1.0
        env:
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-arc-onboarding
              key: TENANT_ID
        - name: SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: azure-arc-onboarding
              key: SUBSCRIPTION_ID
        - name: RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: azure-arc-onboarding
              key: RESOURCE_GROUP
        - name: CONNECTED_CLUSTER
          valueFrom:
            secretKeyRef:
              name: azure-arc-onboarding
              key: CONNECTED_CLUSTER
        - name: LOCATION
          valueFrom:
            secretKeyRef:
              name: azure-arc-onboarding
              key: LOCATION
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-arc-onboarding
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-arc-onboarding
              key: CLIENT_SECRET
      restartPolicy: Never
  backoffLimit: 4
