apiVersion: v1
kind: Secret
metadata:
  name: guard-intergration
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: "EnsureExists"
data:
  TENANT_ID: {{ContainerConfigBase64 "tenantID"}}
  SUBSCRIPTION_ID: {{ContainerConfigBase64 "subscriptionID"}}
  RESOURCE_GROUP: {{ContainerConfigBase64 "resourceGroup"}}
  CONNECTED_CLUSTER: {{ContainerConfigBase64 "clusterName"}}
  LOCATION: {{ContainerConfigBase64 "location"}}
  CLIENT_ID: {{ContainerConfigBase64 "clientID"}}
  CLIENT_SECRET: {{ContainerConfigBase64 "clientSecret"}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guard-intergration
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: "EnsureExists"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guardRoleBinding
  labels:
    addonmanager.kubernetes.io/mode: "EnsureExists"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: guard-intergration
    namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: guard-intergration
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: "EnsureExists"
spec:
  template:
    spec:
      volumes:
      - name: guard-manifests
        hostPath:
          path: /etc/kubernetes
      serviceAccountName: guard-intergration
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: guard-intergration
        image: {{ContainerImage "guard"}}
        volumeMounts:
        - name: guard-manifests
          mountPath: /etc/kubernetes
        env:
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: guard-intergration
              key: TENANT_ID
        - name: SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: guard-intergration
              key: SUBSCRIPTION_ID
        - name: RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: guard-intergration
              key: RESOURCE_GROUP
        - name: CONNECTED_CLUSTER
          valueFrom:
            secretKeyRef:
              name: guard-intergration
              key: CONNECTED_CLUSTER
        - name: LOCATION
          valueFrom:
            secretKeyRef:
              name: guard-intergration
              key: LOCATION
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: guard-intergration
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: guard-intergration
              key: CLIENT_SECRET
      restartPolicy: Never
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: "true"
        effect: NoSchedule
      - operator: "Exists"
        effect: NoExecute
      - operator: "Exists"
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/role: master
        kubernetes.io/os: linux

  backoffLimit: 4
