---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
  name: elb
  namespace: kube-system
spec:
  ports:
  - port: 8765
    targetPort: 9376
    protocol: TCP
  selector:
    app: "<svcName>"
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
  name: elb-udp
  namespace: kube-system
spec:
  ports:
  - port: 8765
    targetPort: 9376
    protocol: UDP
  selector:
    app: "<svcName>"
  type: LoadBalancer