run:
  deadline: 3m
  skip-dirs:
    - test/i18n
    - pkg/test
  skip-files:
    - pkg/i18n/i18n.go
    - pkg/i18n/translations.go
    - exclude pkg/engine/templates.go

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gosimple
    - golint
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused

linters-settings:
  govet:
    check-shadowing: true
