codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 0.5
    patch:
      default:
        threshold: 0.5
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "**/*_generated.go"
  - "test/**/*.go"
  - "pkg/api/mocks.go"
  - "pkg/armhelpers/azurestack/httpMockClient.go"
  - "pkg/armhelpers/azurestack/testserver/testServer.go"
  - "pkg/armhelpers/mockclients.go"
  - "pkg/engine/testutils.go"
  - "pkg/test/*.go"
  - "pkg/engine/engine_dcos.go"
  - "pkg/engine/templates_generated.go"
  - "pkg/i18n/translations_generated.go"
