trigger: none
pr: none

stages:

  - stage: build_2019_containerd
    dependsOn: []
    jobs:
    - template: vhd-builder-windows-template.yaml
      parameters:
        containerRuntime: containerd
        windowsServerVersion: 2019

  - stage: build_2019_docker
    dependsOn: []
    jobs:
    - template: vhd-builder-windows-template.yaml
      parameters:
        containerRuntime: docker
        windowsServerVersion: 2019

  - stage: publish_2019_containerd
    dependsOn: build_2019_containerd
    jobs:
    - template: vhd-publish-template.yaml
      parameters:
        containerRuntime: containerd
        skuPrefix: '2019-datacenter-core-ctrd'
        windowsServerVersion: 2019

  - stage: publish_2019_docker
    dependsOn: build_2019_docker
    jobs:
    - template: vhd-publish-template.yaml
      parameters:
        containerRuntime: docker
        skuPrefix: '2019-datacenter-core-smalldisk'
        windowsServerVersion: 2019
