# Required pipeline variables:
# - AZURE_LOCATION - Azure region to create resources in
# - AZURE_RESOURCE_GROUP_NAME - Resource group to create resources in
# - BUILD_POOL - Azure DevOps build pool to use
# - CLIENT_ID - Service principal ID
# - CLIENT_SECRET - Service principal secret
# - COPY_VHD - Set to 'True' if VHD should be copied to classic storage account in preparation for publishing
# - DEIS_GO_DEV_IMAGE - Dev container image ID
# - PACKER_VM_SIZE - VM Size to be used during packer build operation
# - STORAGE_ACCT_BLOB_URL - Url to blob storage container used to copy image to in preparation for publishing
# - STORAGE_ACCT_SAS_TOKEN - SAS token with permission to write to CLASSIC_BLOB container
# - SUBSCRIPTION_ID - Subscription ID used by the pipeline
# - TENANT_ID - Tenant Id used for service principal login

trigger: none
pr: none

stages:
  - stage: build-2019-containerd
    dependsOn: []
    jobs:
    - template: vhd-builder-windows-template.yaml
      parameters:
        containerRuntime: containerd
        windowsServerVersion: 2019

  - stage: build-2019-docker
    dependsOn: []
    jobs:
    - template: vhd-builder-windows-template.yaml
      parameters:
        containerRuntime: docker
        windowsServerVersion: 2019

